name: Go

on: [push]

jobs:
  go-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19', '1.23.0' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Test
        run: go test
