// Code generated by mockery v2.40.2. DO NOT EDIT.

package testdata

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSliceyThing is an autogenerated mock type for the SliceyThing type
type MockSliceyThing struct {
	mock.Mock
}

type MockSliceyThing_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSliceyThing) EXPECT() *MockSliceyThing_Expecter {
	return &MockSliceyThing_Expecter{mock: &_m.Mock}
}

// DoThing provides a mock function with given fields: _a0, _a1
func (_m *MockSliceyThing) DoThing(_a0 context.Context, _a1 []int) ([]int, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DoThing")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int) ([]int, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int) []int); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSliceyThing_DoThing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoThing'
type MockSliceyThing_DoThing_Call struct {
	*mock.Call
}

// DoThing is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []int
func (_e *MockSliceyThing_Expecter) DoThing(_a0 interface{}, _a1 interface{}) *MockSliceyThing_DoThing_Call {
	return &MockSliceyThing_DoThing_Call{Call: _e.mock.On("DoThing", _a0, _a1)}
}

func (_c *MockSliceyThing_DoThing_Call) Run(run func(_a0 context.Context, _a1 []int)) *MockSliceyThing_DoThing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]int))
	})
	return _c
}

func (_c *MockSliceyThing_DoThing_Call) Return(_a0 []int, _a1 error) *MockSliceyThing_DoThing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSliceyThing_DoThing_Call) RunAndReturn(run func(context.Context, []int) ([]int, error)) *MockSliceyThing_DoThing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSliceyThing creates a new instance of MockSliceyThing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSliceyThing(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSliceyThing {
	mock := &MockSliceyThing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
