// Code generated by mockery v2.40.2. DO NOT EDIT.

package testdata

import mock "github.com/stretchr/testify/mock"

// MockEmptyThing is an autogenerated mock type for the EmptyThing type
type MockEmptyThing struct {
	mock.Mock
}

type MockEmptyThing_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmptyThing) EXPECT() *MockEmptyThing_Expecter {
	return &MockEmptyThing_Expecter{mock: &_m.Mock}
}

// DoThing provides a mock function with given fields:
func (_m *MockEmptyThing) DoThing() {
	_m.Called()
}

// MockEmptyThing_DoThing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoThing'
type MockEmptyThing_DoThing_Call struct {
	*mock.Call
}

// DoThing is a helper method to define mock.On call
func (_e *MockEmptyThing_Expecter) DoThing() *MockEmptyThing_DoThing_Call {
	return &MockEmptyThing_DoThing_Call{Call: _e.mock.On("DoThing")}
}

func (_c *MockEmptyThing_DoThing_Call) Run(run func()) *MockEmptyThing_DoThing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEmptyThing_DoThing_Call) Return() *MockEmptyThing_DoThing_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEmptyThing_DoThing_Call) RunAndReturn(run func()) *MockEmptyThing_DoThing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEmptyThing creates a new instance of MockEmptyThing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmptyThing(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmptyThing {
	mock := &MockEmptyThing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
