// Code generated by mockery v2.40.2. DO NOT EDIT.

package obj

import mock "github.com/stretchr/testify/mock"

// MockObj is an autogenerated mock type for the Obj type
type MockObj struct {
	mock.Mock
}

type MockObj_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObj) EXPECT() *MockObj_Expecter {
	return &MockObj_Expecter{mock: &_m.Mock}
}

// DoThing provides a mock function with given fields: a, b
func (_m *MockObj) DoThing(a int, b int) (int, error) {
	ret := _m.Called(a, b)

	if len(ret) == 0 {
		panic("no return value specified for DoThing")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(int, int) (int, error)); ok {
		return rf(a, b)
	}
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(a, b)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObj_DoThing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoThing'
type MockObj_DoThing_Call struct {
	*mock.Call
}

// DoThing is a helper method to define mock.On call
//   - a int
//   - b int
func (_e *MockObj_Expecter) DoThing(a interface{}, b interface{}) *MockObj_DoThing_Call {
	return &MockObj_DoThing_Call{Call: _e.mock.On("DoThing", a, b)}
}

func (_c *MockObj_DoThing_Call) Run(run func(a int, b int)) *MockObj_DoThing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockObj_DoThing_Call) Return(_a0 int, _a1 error) *MockObj_DoThing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObj_DoThing_Call) RunAndReturn(run func(int, int) (int, error)) *MockObj_DoThing_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObj creates a new instance of MockObj. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObj(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObj {
	mock := &MockObj{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
